---
# Secret admin pour PostgreSQL (utilisé par le Deployment postgres).
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
  namespace: fraud-detection-ml
type: Opaque
stringData:
  POSTGRES_DB: feast_db
  POSTGRES_USER: feast_user
  POSTGRES_PASSWORD: <CHANGEZ_MOI>
---
# Secret pour le online store PostgreSQL.
# Le Feast operator attend une clé unique nommée d'après le type de store ("postgres")
# contenant les paramètres de connexion au format YAML.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: fraud-detection-ml
type: Opaque
stringData:
  postgres: |
    host: postgres.fraud-detection-ml.svc.cluster.local
    port: 5432
    user: feast_user
    password: <CHANGEZ_MOI>
    database: feast_db
---
# Secret admin MinIO (utilisé par le Deployment minio et le Job bucket).
apiVersion: v1
kind: Secret
metadata:
  name: minio-admin
  namespace: fraud-detection-ml
type: Opaque
stringData:
  MINIO_ROOT_USER: <CHANGEZ_MOI>
  MINIO_ROOT_PASSWORD: <CHANGEZ_MOI>
---
# Credentials S3/MinIO pour le registry Feast.
# Ces variables d'environnement sont injectées dans les pods Feast
# via envFrom dans le FeatureStore CR.
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: fraud-detection-ml
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <CHANGEZ_MOI>
  AWS_SECRET_ACCESS_KEY: <CHANGEZ_MOI>
  AWS_ENDPOINT_URL: http://minio.fraud-detection-ml.svc.cluster.local:9000
  AWS_DEFAULT_REGION: us-east-1
