---
# ServiceAccount utilisé par le CronJob Feast pour exécuter
# feast apply et feast materialize-incremental via kubectl exec.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feast-fraud-features
  namespace: fraud-detection-ml
---
# Role permettant au CronJob d'exécuter des commandes
# dans les pods Feast via kubectl exec.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: feast-fraud-features-cronjob
  namespace: fraud-detection-ml
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: feast-fraud-features-cronjob
  namespace: fraud-detection-ml
subjects:
  - kind: ServiceAccount
    name: feast-fraud-features
    namespace: fraud-detection-ml
roleRef:
  kind: Role
  name: feast-fraud-features-cronjob
  apiGroup: rbac.authorization.k8s.io
---
# Role pour le Feature Store (gestion des secrets, configmaps, services)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: feast-fraud-features
  namespace: fraud-detection-ml
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["feast.dev"]
    resources: ["featurestores"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: feast-fraud-features
  namespace: fraud-detection-ml
subjects:
  - kind: ServiceAccount
    name: feast-fraud-features
    namespace: fraud-detection-ml
roleRef:
  kind: Role
  name: feast-fraud-features
  apiGroup: rbac.authorization.k8s.io
---
# Roles Feast RBAC pour le controle d'acces aux features
# Ces roles sont references dans le FeatureStore CR (authz.kubernetes.roles)
# et dans permissions.py (RoleBasedPolicy)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: feast-writer
  namespace: fraud-detection-ml
rules:
  - apiGroups: ["feast.dev"]
    resources: ["featurestores"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: feast-reader
  namespace: fraud-detection-ml
rules:
  - apiGroups: ["feast.dev"]
    resources: ["featurestores"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
# RoleBinding feast-writer pour le dashboard
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: feast-writer-dashboard
  namespace: fraud-detection-ml
subjects:
  - kind: ServiceAccount
    name: rhods-dashboard
    namespace: redhat-ods-applications
roleRef:
  kind: Role
  name: feast-writer
  apiGroup: rbac.authorization.k8s.io
---
# RoleBinding feast-reader pour tous les utilisateurs authentifies
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: feast-reader-authenticated
  namespace: fraud-detection-ml
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: feast-reader
  apiGroup: rbac.authorization.k8s.io
---
# RoleBinding feast-reader pour tous les ServiceAccounts du namespace
# (necessaire car Feast RBAC resout les roles par SA, pas par groupe)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: feast-reader-namespace-sa
  namespace: fraud-detection-ml
subjects:
  - kind: Group
    name: system:serviceaccounts:fraud-detection-ml
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: feast-reader
  apiGroup: rbac.authorization.k8s.io
