---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: fraud-features
  namespace: fraud-detection-ml
  labels:
    feature-store-ui: enabled
spec:
  feastProject: fraud_detection
  feastProjectDir:
    git:
      url: https://github.com/mouachan/fraud-detection-ml
      ref: main
      subPath: feature_repo
  authz:
    kubernetes:
      roles:
        - feast-writer
        - feast-reader
  services:
    onlineStore:
      persistence:
        store:
          type: postgres
          secretRef:
            name: postgres-creds
      server:
        envFrom:
          - secretRef:
              name: minio-creds
    registry:
      local:
        server:
          restAPI: true
          envFrom:
            - secretRef:
                name: minio-creds
        persistence:
          file:
            path: s3://feast-registry/registry.db
    ui:
      envFrom:
        - secretRef:
            name: minio-creds
